In [9]:
## ✅ update access token every hour
# ✅ Fetches 2000 posts per hashtag using pagination
# ✅ Uses one request per media load (limits = 100 per request)
# ✅ Automatically handles API rate limits
# ✅ Appends data to one JSON file
import requests
import json
import time
import os

# --- CONFIGURATION ---
ACCESS_TOKEN = "EAAVx7qOTMZBcBOZBf8qMLWGZAI8ZAGZCEGOu4Pya02F0tLrzCVlZCOtexsLd3AZBuA1CMZBsDsUSF4kKpwAaRxzaTnTX7aLZA4auZBeOl1l3cn0pBk1xmJ4LDOSQzZAChMZCKV2WOn7lKTz09ZB73TXFoh0bD2QlV1LwRzn9sW9ZCFARZBNtrfuu3AmxlZAA97Mip0iKoD5iocuvMpAdCY9BlNwkorx5qCWsv4QyMfGYwqEZD"
USER_ID = "17841468142856047"  # Replace with your Instagram Business Account ID
POSTS_PER_HASHTAG = 10000 # Number of posts to fetch per hashtag
BATCH_SIZE = 50  # Max limit per request

JSON_FILENAME = "beauty2.json"

# Get multiple hashtags from user
hashtags = input("Enter hashtags separated by commas (without #): ").strip().split(',')

# --- HELPER FUNCTIONS ---
def get_hashtag_id(hashtag_name, user_id, access_token):
    """Fetch the Instagram hashtag ID for a given hashtag name."""
    url = f"https://graph.facebook.com/v22.0/ig_hashtag_search?user_id={user_id}&q={hashtag_name.strip()}&access_token={access_token}"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        return data["data"][0]["id"] if "data" in data and data["data"] else None
    except requests.exceptions.RequestException as e:
        print(f"Error fetching hashtag ID for #{hashtag_name}: {e}")
        return None

def fetch_posts(hashtag_id, user_id, access_token, max_posts):
    """Fetch up to max_posts using pagination."""
    url = (f"https://graph.facebook.com/v22.0/{hashtag_id}/top_media?"
           f"fields=caption,like_count,media_url,media_product_type,permalink,id&"
           f"user_id={user_id}&limit={BATCH_SIZE}&access_token={access_token}")
    
    posts = []
    total_fetched = 0

    while url and total_fetched < max_posts:
        try:
            response = requests.get(url)
            response.raise_for_status()
            data = response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error during request: {e}")
            break

        batch = data.get("data", [])
        if not batch:
            print("No more posts found.")
            break

        posts.extend(batch[:max_posts - total_fetched])
        total_fetched += len(batch)

        print(f"Fetched {len(batch)} new posts (Total: {total_fetched}/{max_posts})")

        # Check for pagination
        url = data.get("paging", {}).get("next")
        time.sleep(1)  # Prevent hitting rate limits

    return posts

# Load existing data if file exists
if os.path.exists(JSON_FILENAME):
    with open(JSON_FILENAME, "r", encoding="utf-8") as jsonfile:
        try:
            existing_data = json.load(jsonfile)
        except json.JSONDecodeError:
            existing_data = {"data": []}
else:
    existing_data = {"data": []}

# --- MAIN SCRIPT ---
for hashtag in hashtags:
    hashtag = hashtag.strip()
    if not hashtag:
        continue

    print(f"\nProcessing #{hashtag}...")

    # Get Hashtag ID
    hashtag_id = get_hashtag_id(hashtag, USER_ID, ACCESS_TOKEN)
    if not hashtag_id:
        print(f"Skipping #{hashtag} (ID not found).")
        continue

    print(f"Fetched Hashtag ID for #{hashtag}: {hashtag_id}")

    # Fetch posts with pagination
    posts = fetch_posts(hashtag_id, USER_ID, ACCESS_TOKEN, POSTS_PER_HASHTAG)
    if not posts:
        print(f"No posts found for #{hashtag}.")
        continue

    # Append fetched data
    existing_data["data"].extend(posts)
    print(f"Added {len(posts)} records for #{hashtag}.")

    # Wait to avoid rate limits
    time.sleep(2)

# Save all data to JSON
with open(JSON_FILENAME, "w", encoding="utf-8") as jsonfile:
    json.dump(existing_data, jsonfile, indent=4)

print(f"\nData collection complete. All records saved in '{JSON_FILENAME}'.")

Processing #indianskincare...
Fetched Hashtag ID for #indianskincare: 17841545905094640
Fetched 50 new posts (Total: 50/10000)
Fetched 50 new posts (Total: 100/10000)
Fetched 50 new posts (Total: 150/10000)
Fetched 50 new posts (Total: 200/10000)
Fetched 50 new posts (Total: 250/10000)

KeyboardInterrupt:

In [4]:
JSON_FILENAME="beauty.json"

### 📌 Now we will print our dataset collected 📝

In [5]:

import pandas as pd
import json

# Load JSON file
with open(JSON_FILENAME, "r", encoding="utf-8") as file:
    data = json.load(file)

# Normalize the JSON data
df = pd.json_normalize(data["data"])  # Extracts data inside "data" key

# Select required columns
df = df[["caption", "like_count", "media_url", "media_product_type", "permalink", "id"]]

# Save the structured data to CSV
# df.to_csv("output.csv", index=False)
df

,caption,like_count,media_url,media_product_type,permalink,id
0,Episode - 97 of Meme Xpress Unknown Facts...\n...,1364.0,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/DFAtJJHzD67/,18277799980300139
1,Vineeta Singh An IIM Alumus had declined Rs 1 ...,4358.0,https://scontent.cdninstagram.com/v/t51.2885-1...,FEED,https://www.instagram.com/p/Cb_sr2-uJ8U/,17956447813676941
2,Adding iPhone to this list . Raise your hands ...,1197.0,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/CY6al7iLh9W/,18189775927159145
3,winter am routine❄️\n\ncetaphil_india gentle c...,879.0,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/Cma6JKfhNmS/,17952732260181270
4,A few other things to note -\n\n1. Damp skin m...,22831.0,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/CjDx2EkrNfz/,17991528778513919
...,...,...,...,...,...,...
7290,Delivering now: Your at-home facial ritual to ...,658.0,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/CkBgZeoMTAC/,17987822947608958
7291,Is that a scoop of ice cream or Red Vine Face ...,347.0,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/Ci2yF0BsUZY/,17976692557732310
7292,Get the ultimate sun protection every time you...,471.0,https://scontent.cdninstagram.com/v/t51.2885-1...,FEED,https://www.instagram.com/p/Cj20FRrvSMf/,17946422726507448
7293,Clinkin’ cuz the weekend is here! 🥂\n.\nGet fe...,920.0,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/CUfKavjMRgW/,17913898388051859
7294,Review Time❤\n\nI received these two beautiful...,698.0,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/CZjOAtCPgI7/,17890657550580336

In [ ]:
i want you update the code for taking the permalink column and like_count as in the image shown from the file named:beauty.json by loading in normalized form and run the script for fetch username and append the data in fileindianskincare.csv file with column username,(like_count cloumn ) with  appended suffixes like/view according to the permalink type you detect by your self by logic of tv/p/reel etc and correspond permalink column used ,update in the code but not change the xpath for finding username:

### 📌 Now we wil remove duplicate posts having same media id📝

In [9]:

# Display the first few rows
df
column_name = 'id'  # Change this to any column you want to check

# Count total duplicate values (excluding unique ones)
total_duplicates = df[column_name].duplicated().sum()

print(f"Total duplicate values in column '{column_name}': {total_duplicates}")

Total duplicate values in column 'id': 0

In [10]:
with open(JSON_FILENAME, "r", encoding="utf-8") as file:
    data = json.load(file)

# Convert JSON to DataFrame
df = pd.DataFrame(data["data"])

if df.empty:
    print("No data found in the JSON file.")
else:
    # Count total duplicate values before removal
    total_duplicates = df["id"].duplicated().sum()
    print(f"Total duplicate values in column 'id' before removal: {total_duplicates}")

    # Remove duplicate rows based on the 'id' column
    df = df.drop_duplicates(subset="id")

    # Reset row indices
    df = df.reset_index(drop=True)

    # Save cleaned data back to the same JSON file
    cleaned_data = df.to_dict(orient="records")
    with open(JSON_FILENAME, "w", encoding="utf-8") as file:
        json.dump({"data": cleaned_data}, file, indent=4)

    print(f"Duplicates removed. Data saved back to '{JSON_FILENAME}'.\n")
    print(df.head())

    # Display the first few rows after cleaning

Total duplicate values in column 'id' before removal: 0
Duplicates removed. Data saved back to 'beauty.json'.

                                             caption  \
0  Day 3/365 #ReStartwGur \nBaddie Back in the Be...
1  🩵 glam room selfies \n.\n.\n.\n.\n#bts #blueli...
2  Elegance of this beautiful hand painted organz...
3  ✨GIVEAWAY ALERT✨ CLOSED\n\nI have got the DREA...
4                                                  💚

                                           media_url media_product_type  \
0  https://scontent.cdninstagram.com/v/t51.29350-...               FEED
1  https://scontent.cdninstagram.com/v/t51.29350-...               FEED
2  https://scontent.cdninstagram.com/v/t51.29350-...               FEED
3  https://scontent.cdninstagram.com/v/t51.29350-...               FEED
4  https://scontent.cdninstagram.com/v/t51.29350-...               FEED

                                  permalink                 id  like_count
0  https://www.instagram.com/p/C3KIeiPu6a7/  17951805287635639         NaN
1  https://www.instagram.com/p/CuCLF2ep8hE/  17972038775393749       563.0
2  https://www.instagram.com/p/Cq5sQkgIYF-/  18005653312718386      8085.0
3  https://www.instagram.com/p/CmyfjbhpLzT/  17902370273641548      2196.0
4  https://www.instagram.com/p/Cr9_9HWS9YJ/  18192248482266050       293.0

In [11]:
print("total unique records:", len(df))

total unique records: 555

In [12]:
df

,caption,media_url,media_product_type,permalink,id,like_count
0,Day 3/365 #ReStartwGur \nBaddie Back in the Be...,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/C3KIeiPu6a7/,17951805287635639,NaN
1,🩵 glam room selfies \n.\n.\n.\n.\n#bts #blueli...,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/CuCLF2ep8hE/,17972038775393749,563.0
2,Elegance of this beautiful hand painted organz...,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/Cq5sQkgIYF-/,18005653312718386,8085.0
3,✨GIVEAWAY ALERT✨ CLOSED\n\nI have got the DREA...,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/CmyfjbhpLzT/,17902370273641548,2196.0
4,💚,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/Cr9_9HWS9YJ/,18192248482266050,293.0
...,...,...,...,...,...,...
550,"Pyaara gaanaa, Pyaari Main. ❤️✨ \n\nShubho Mah...",https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/CyXbfWbJdsS/,17910141599765357,3289.0
551,"In these 4 walls, my thoughts are safe and I a...",https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/ClT1-OES7OL/,17964151456916597,2446.0
552,See this tip change your skin care game! ✨\n\n...,https://instagram.fdel11-2.fna.fbcdn.net/o1/v/...,FEED,https://www.instagram.com/tv/CcSGm9Chms1/,17972613301548764,662.0
553,"""FRESH beauty secrets!"" 🌿\n\nInspired by the c...",https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/ChZmYbstJXa/,18046736068355198,506.0
554,Client Diaries #FlauntingAlpsNails 💕 - our BES...,https://scontent.cdninstagram.com/v/t51.29350-...,FEED,https://www.instagram.com/p/ClA1TPphgDB/,17906675012667891,437.0

### 📌 Now we will print permalinks and extract shortcodes 📝

In [13]:
df["permalink"]

0       https://www.instagram.com/p/C3KIeiPu6a7/
1       https://www.instagram.com/p/CuCLF2ep8hE/
2       https://www.instagram.com/p/Cq5sQkgIYF-/
3       https://www.instagram.com/p/CmyfjbhpLzT/
4       https://www.instagram.com/p/Cr9_9HWS9YJ/
                         ...
550     https://www.instagram.com/p/CyXbfWbJdsS/
551     https://www.instagram.com/p/ClT1-OES7OL/
552    https://www.instagram.com/tv/CcSGm9Chms1/
553     https://www.instagram.com/p/ChZmYbstJXa/
554     https://www.instagram.com/p/ClA1TPphgDB/
Name: permalink, Length: 555, dtype: object

In [14]:
# Extract shortcodes from df["permalink"]
shortcodes = df["permalink"].apply(lambda x: x.split("/")[-2].split("?")[0])

# Print the shortcodes series
print(shortcodes)

# Check if the series is empty
if shortcodes.empty:
    print("The shortcodes series is empty.")
else:
    # Create a new DataFrame with the shortcodes
    shortcodes_df = pd.DataFrame(shortcodes, columns=["shortcode"])
    print(shortcodes_df)

0      C3KIeiPu6a7
1      CuCLF2ep8hE
2      Cq5sQkgIYF-
3      CmyfjbhpLzT
4      Cr9_9HWS9YJ
          ...
550    CyXbfWbJdsS
551    ClT1-OES7OL
552    CcSGm9Chms1
553    ChZmYbstJXa
554    ClA1TPphgDB
Name: permalink, Length: 555, dtype: object
Empty DataFrame
Columns: [shortcode]
Index: []

In [15]:
print(type(shortcodes))
print(shortcodes)

<class 'pandas.core.series.Series'>
0      C3KIeiPu6a7
1      CuCLF2ep8hE
2      Cq5sQkgIYF-
3      CmyfjbhpLzT
4      Cr9_9HWS9YJ
          ...
550    CyXbfWbJdsS
551    ClT1-OES7OL
552    CcSGm9Chms1
553    ChZmYbstJXa
554    ClA1TPphgDB
Name: permalink, Length: 555, dtype: object

### 📌 Now we will extract the usernames of the posts  📝

In [18]:
import time
import random
import pandas as pd
from instaloader import Instaloader, Post

# Initialize Instaloader
L = Instaloader()

# Load shortcodes from a CSV file (if needed)
# shortcodes = ["CximKgfq-Gu", "Ci98q31LR2i", "DBBX9kUzFXf", "DCI-p6Xv_OA"]  # Replace with your shortcode list

# Output file name
output_file = "output2.csv"

# Load existing data to avoid duplicates
try:
    existing_data = pd.read_csv(output_file)
    processed_shortcodes = set(existing_data["shortcodes"])
except FileNotFoundError:
    processed_shortcodes = set()

# Create an empty list to store results
results = []

# Initialize retry settings
max_retries = 5
initial_wait_time = 30  # Initial wait time in seconds for backoff

# Iterate over each shortcode
for shortcode in shortcodes:
    if shortcode in processed_shortcodes:
        print(f"Skipping {shortcode}, already processed.")
        continue  # Skip already processed shortcodes

    retries = 0
    wait_time = initial_wait_time

    while retries < max_retries:
        try:
            # Fetch the post details using the shortcode
            post = Post.from_shortcode(L.context, shortcode)

            # Get the owner's profile
            owner_profile = post.profile
            print(f"Fetched: {owner_profile}")

            # Append the result to the list
            results.append({
                "shortcodes": shortcode,
                "username": owner_profile  # Extract username
            })

            # Save the result to a CSV file efficiently
            pd.DataFrame(results[-1:], columns=["shortcode", "owner_profile"]).to_csv(
                output_file, mode='a', header=not processed_shortcodes, index=False
            )

            # Add to processed set
            processed_shortcodes.add(shortcode)

            # Randomized delay to avoid rate limits (3 to 8 sec)
            time.sleep(random.uniform(3, 8))
            break  # Move to next shortcode

        except Exception as e:
            error_msg = str(e)
            print(f"Error processing {shortcode}: {error_msg}")

            # If 401 Unauthorized, wait and retry
            if "401 Unauthorized" in error_msg or "Please wait a few minutes" in error_msg:
                print(f"Rate limit hit! Retrying in {wait_time} seconds...")
                time.sleep(wait_time)
                wait_time *= 2  # Exponential backoff
                retries += 1
            else:
                # If another error, move to the next shortcode
                break

print("✅ Process completed successfully!")

Skipping C3KIeiPu6a7, already processed.
Skipping CuCLF2ep8hE, already processed.
Skipping Cq5sQkgIYF-, already processed.
Skipping CmyfjbhpLzT, already processed.
Skipping Cr9_9HWS9YJ, already processed.

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Ckx7moqIb-s: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 30 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Ckx7moqIb-s: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 60 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Ckx7moqIb-s: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 120 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Ckx7moqIb-s: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 240 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Ckx7moqIb-s: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Ckx7moqIb-s%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 480 seconds...
Skipping DAyH6Eazov-, already processed.
Skipping Ch9brkmveo_, already processed.
Skipping DB0WiukP4_p, already processed.
Skipping Cm50Jg5rzMy, already processed.
Skipping CjQZwLII24s, already processed.
Skipping CstPapIpJNv, already processed.
Skipping Cn34riPPMXQ, already processed.
Skipping CqNdn9XIEC4, already processed.
Skipping DBS-ZfcJI4_, already processed.
Skipping CohJTiDy5Tp, already processed.
Skipping ClX8DjcMgSx, already processed.
Skipping CqM3H7DSfxo, already processed.
Skipping CjnhTThvclR, already processed.
Skipping CoYz_q2ox3x, already processed.
Skipping CnOWdocSbY9, already processed.
Skipping Cu8sY8hsE-c, already processed.
Skipping CnGeZmiPZpd, already processed.
Skipping DEUmlj1THdc, already processed.
Skipping Cim35uRpOSa, already processed.
Skipping CdSloMap_Es, already processed.
Skipping CpM0GmkrNUk, already processed.
Skipping Co4oyjxShS0, already processed.
Skipping DCEuegiSUfp, already processed.
Skipping DBifeYHxHsN, already processed.
Skipping C0bY8ICIsHv, already processed.
Skipping CymjNj8vv73, already processed.
Skipping DC50Tu4otVJ, already processed.
Skipping CrFXgEjvQEj, already processed.
Skipping C2zsEHzSS4P, already processed.
Skipping DDErVWqz27b, already processed.
Skipping CqSzvKhvWa3, already processed.
Skipping CpqOaXwN8fp, already processed.
Skipping C1l5TYQy-1o, already processed.
Skipping CtYF08Gr2TL, already processed.
Skipping ClVtBYXpd7Z, already processed.
Skipping CzG6_hkSTu_, already processed.
Skipping CsjQP5sp4je, already processed.
Skipping CoChJWsDQP3, already processed.
Skipping CqGUF2aMtYD, already processed.
Skipping DFNbdopzfve, already processed.
Skipping Ck3mEx4hNvW, already processed.
Skipping CmLdyo6LvFD, already processed.
Skipping CyK0JYvpuIh, already processed.
Skipping Ck8X44DpNYj, already processed.
Skipping C21l91MSD7c, already processed.
Skipping Ctn10-BqimP, already processed.
Skipping Cw-olrhKeBt, already processed.
Skipping CiUUBMirFGl, already processed.
Skipping Chl0QMPrJ0e, already processed.
Skipping CpCy3JvpILv, already processed.
Skipping CzG3YntJicC, already processed.
Skipping CjNpqgCq8Bh, already processed.
Skipping DCeklEbTfkH, already processed.
Skipping CwzWMAEInXy, already processed.
Skipping Cm8jy_Mrb2Q, already processed.
Skipping CiNUhZQpO4V, already processed.
Skipping CkyPnThyGBH, already processed.
Skipping Cq0A8xmJCkf, already processed.
Skipping CdA1SFJogag, already processed.
Skipping CiRvpafJZFr, already processed.
Skipping CflL0yRl7e0, already processed.
Skipping CoW-k-3pwSh, already processed.
Skipping C4A4cWuSZ8g, already processed.

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwNJThnsEFI: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 30 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwNJThnsEFI: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 60 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwNJThnsEFI: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 120 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwNJThnsEFI: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 240 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwNJThnsEFI: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwNJThnsEFI%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 480 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C2yyKdtJOp-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 30 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C2yyKdtJOp-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 60 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C2yyKdtJOp-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 120 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C2yyKdtJOp-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 240 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C2yyKdtJOp-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C2yyKdtJOp-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 480 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CpDYZHISQqU: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 30 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CpDYZHISQqU: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 60 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CpDYZHISQqU: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 120 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CpDYZHISQqU: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 240 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CpDYZHISQqU: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CpDYZHISQqU%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 480 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Cph3Z-pyDXC: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 30 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Cph3Z-pyDXC: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 60 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Cph3Z-pyDXC: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 120 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Cph3Z-pyDXC: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 240 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing Cph3Z-pyDXC: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22Cph3Z-pyDXC%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 480 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C1kN6SXyPPo: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 30 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C1kN6SXyPPo: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 60 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C1kN6SXyPPo: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 120 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C1kN6SXyPPo: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 240 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing C1kN6SXyPPo: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22C1kN6SXyPPo%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 480 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwcwHNZKqT-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 30 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwcwHNZKqT-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 60 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwcwHNZKqT-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 120 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwcwHNZKqT-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 240 seconds...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true [retrying; skip with ^C]

Error processing CwcwHNZKqT-: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22shortcode%22%3A%22CwcwHNZKqT-%22%7D&doc_id=8845758582119845&server_timestamps=true
Rate limit hit! Retrying in 480 seconds...

KeyboardInterrupt:

---
## 🔍 Now we will check for unique usernames  📊
---

In [ ]:
import pandas as pd

# Load CSV file
# Change this to your actual file path
df = pd.read_csv(output_file)

# Check for duplicate usernames
duplicates = df.duplicated(subset=['usernames'])  # Check for duplicates in 'username' column
total_duplicates = duplicates.sum()
print(f"Total duplicate usernames found: {total_duplicates}")

# Remove duplicates
df_cleaned = df.drop_duplicates(subset=['usernames'], keep='first')

# Print total records after removing duplicates
print(f"Total records after removing duplicates: {len(df_cleaned)}")

# Save the cleaned data back to the same file
df_cleaned.to_csv(file_path, index=False)

print("Duplicates removed and file updated successfully.")

In [ ]:
import pandas as pd
data_total=pd.read_csv("output.csv")
print(len(data_total))

In [30]:
# import pandas as pd

# # Your list of hashtags
# hashtags = ['#skincareindia', '#naturalskincareindia', '#skincareroutineindia', '#skincaretipsindia', '#indianskincareblogger',
#             '#glowingskinindia', '#skincareproductsindia', '#ayurvedaskinindia','#skincareproductsindia', '#GlowingSkinindia', '#SkincareRoutineidia', '#sunscreenindian', 
#             '#sunscreeneverydayindia', '#skindetanindia', '#indianskincare', '#pigmentationindia', 
#             '#darkspotsindia', '#sunscreenindia']
# # Remove the '#' symbol from each hashtag
# cleaned_hashtags = [hashtag.lstrip('#') for hashtag in hashtags]

# # Create a DataFrame with the cleaned hashtags
# df = pd.DataFrame(cleaned_hashtags, columns=['hashtagslist'])

# # Save to CSV
# df.to_csv('skincarehashtags.csv', index=False)

# print("CSV file has been saved successfully.")

CSV file has been saved successfully.

In [32]:
# d=pd.read_csv("skincarehashtags.csv")
# d

              hashtagslist
0            skincareindia
1     naturalskincareindia
2     skincareroutineindia
3        skincaretipsindia
4    indianskincareblogger
5         glowingskinindia
6    skincareproductsindia
7        ayurvedaskinindia
8    skincareproductsindia
9         GlowingSkinindia
10     SkincareRoutineidia
11         sunscreenindian
12  sunscreeneverydayindia
13          skindetanindia
14          indianskincare
15       pigmentationindia
16          darkspotsindia
17          sunscreenindia

In [ ]:
# import pandas as pd
# import csv
# import time
# from instagrapi import Client
# from requests.exceptions import RequestException

# # Instagram credentials
# USERNAME = "aakash_sharma413"
# PASSWORD = "@_&#+(@&@Aakash"  # Replace with your actual password

# # Initialize the Client
# cl = Client()

# # Login to Instagram
# try:
#     cl.login(USERNAME, PASSWORD)
#     print("✅ Login successful!")
# except Exception as e:
#     print(f"❌ Login failed: {e}")
#     exit()  # Stop execution if login fails

# # Read the CSV file containing usernames and hashtags
# df = pd.read_csv('finalusername.csv')

# # Open an output CSV file to write results
# output_file = 'updated_followers2s.csv'

# # Check if the file already exists to decide whether to write a header
# write_header = not pd.io.common.file_exists(output_file)

# with open(output_file, 'a', newline='') as file:
#     csv_writer = csv.writer(file)

#     # Write header if the file is new
#     if write_header:
#         csv_writer.writerow(['Username', 'Hashtag', 'Followers'])

#     # Process data in batches of 5 users to reduce waiting time
#     batch_size = 5
#     for i in range(0, len(df), batch_size):
#         batch = df.iloc[i:i + batch_size]  # Extract a batch of 5 users

#         for index, row in batch.iterrows():
#             usrname = row['Username']
#             hashtag = row['Hashtag']

#             try:
#                 # Fetch followers count using instagrapi
#                 user_id = cl.user_id_from_username(usrname)
#                 user_info = cl.user_info(user_id)
#                 followers = user_info.follower_count

#                 # Print and store data
#                 print(f"Username: {usrname}, Hashtag: {hashtag}, Followers: {followers}")
#                 csv_writer.writerow([usrname, hashtag, followers])

#             except (RequestException, ValueError) as e:
#                 print(f"❌ Error fetching data for {usrname}: {e}")
#                 print(f"⏳ Retrying once...")
#                 time.sleep(5)  # Wait for a bit before retrying
#                 try:
#                     # Retry fetching followers count after the wait
#                     user_id = cl.user_id_from_username(usrname)
#                     user_info = cl.user_info(user_id)
#                     followers = user_info.follower_count

#                     # Print and store data after retry
#                     print(f"Username: {usrname}, Hashtag: {hashtag}, Followers: {followers}")
#                     csv_writer.writerow([usrname, hashtag, followers])

#                 except (RequestException, ValueError) as e:
#                     print(f"❌ Failed again for {usrname}: {e}")
#                     print(f"Skipping {usrname}...")

#         # Reduce waiting time by processing in batches
#         print("⏳ Waiting 5 seconds before processing the next batch...")
#         time.sleep(5)

In [6]:
# #run from next rows
# import pandas as pd
# import csv
# import time
# from instagrapi import Client

# # Instagram credentials
# USERNAME = "aakash_sharma413"
# PASSWORD = "@_&#+(@&@Aakash"  # Replace with your actual password

# # Initialize the Client
# cl = Client()

# # Login to Instagram
# try:
#     cl.login(USERNAME, PASSWORD)
#     print("✅ Login successful!")
# except Exception as e:
#     print(f"❌ Login failed: {e}")
#     exit()  # Stop execution if login fails

# # Read the CSV file containing usernames and hashtags
# df = pd.read_csv('finalusername.csv')

# # Open an output CSV file to write results
# output_file = 'updated_followers2s.csv'

# # Check if the file already exists to decide whether to write a header
# write_header = not pd.io.common.file_exists(output_file)

# with open(output_file, 'a', newline='') as file:
#     csv_writer = csv.writer(file)

#     # Write header if the file is new
#     if write_header:
#         csv_writer.writerow(['Username', 'Hashtag', 'Followers'])

#     # Start processing from the next row after the last processed user
#     start_index = df[df['Username'] == 'al_zenaskincarelasem'].index[0] + 1  # Get the index of the next row

#     # Process the data from the next user onward
#     for index, row in df.iloc[start_index:].iterrows():
#         usrname = row['Username']
#         hashtag = row['Hashtag']

#         try:
#             # Fetch followers count using instagrapi
#             user_id = cl.user_id_from_username(usrname)
#             user_info = cl.user_info(user_id)
#             followers = user_info.follower_count

#             # Print and store data
#             print(f"Username: {usrname}, Hashtag: {hashtag}, Followers: {followers}")
#             csv_writer.writerow([usrname, hashtag, followers])

#         except Exception as e:
#             print(f"❌ Error fetching data for {usrname}: {e}")
        
#         # Optional: If you want to limit requests per minute, you can add a sleep time here, but for now, no delay

✅ Login successful!

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/110_avenue_aubagne/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/110_avenue_aubagne/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/110_avenue_aubagne/?__a=1&__d=dis) >>>

Username: 110_avenue_aubagne, Hashtag: skincareroutine, Followers: 75

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thammachad_official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thammachad_official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thammachad_official/?__a=1&__d=dis) >>>

Username: thammachad_official, Hashtag: skincareroutine, Followers: 19

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sculpt.skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sculpt.skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sculpt.skincare/?__a=1&__d=dis) >>>

Username: sculpt.skincare, Hashtag: skincareroutine, Followers: 710

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/claire_glownglitter/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/claire_glownglitter/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/claire_glownglitter/?__a=1&__d=dis) >>>

Username: claire_glownglitter, Hashtag: skincareroutine, Followers: 12904

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/makeupby_mehakarora/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/makeupby_mehakarora/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/makeupby_mehakarora/?__a=1&__d=dis) >>>

Username: makeupby_mehakarora, Hashtag: skincareroutine, Followers: 221

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cosmenova_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cosmenova_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cosmenova_/?__a=1&__d=dis) >>>

Username: cosmenova_, Hashtag: skincareroutine, Followers: 96

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tirtaayukayoon/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tirtaayukayoon/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tirtaayukayoon/?__a=1&__d=dis) >>>

Username: tirtaayukayoon, Hashtag: skincareroutine, Followers: 3500

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/anndaisycosme_2023/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/anndaisycosme_2023/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/anndaisycosme_2023/?__a=1&__d=dis) >>>

Username: anndaisycosme_2023, Hashtag: skincareroutine, Followers: 160

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/laserskinline/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/laserskinline/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/laserskinline/?__a=1&__d=dis) >>>

Username: laserskinline, Hashtag: skincareroutine, Followers: 1045

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/krumamnarukjung/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/krumamnarukjung/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/krumamnarukjung/?__a=1&__d=dis) >>>

Username: krumamnarukjung, Hashtag: skincareroutine, Followers: 289

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/livnaskin.official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/livnaskin.official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/livnaskin.official/?__a=1&__d=dis) >>>

Username: livnaskin.official, Hashtag: skincareroutine, Followers: 40160

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyhope.sg/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyhope.sg/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyhope.sg/?__a=1&__d=dis) >>>

Username: beautyhope.sg, Hashtag: skincareroutine, Followers: 816

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dixitsuperspecialityhospital/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dixitsuperspecialityhospital/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dixitsuperspecialityhospital/?__a=1&__d=dis) >>>

Username: dixitsuperspecialityhospital, Hashtag: skincareroutine, Followers: 23

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/baxidentalcare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/baxidentalcare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/baxidentalcare/?__a=1&__d=dis) >>>

Username: baxidentalcare, Hashtag: skincareroutine, Followers: 237

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayurvedic_clinic_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayurvedic_clinic_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayurvedic_clinic_/?__a=1&__d=dis) >>>

Username: ayurvedic_clinic_, Hashtag: skincareroutine, Followers: 360

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dermalink.official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dermalink.official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dermalink.official/?__a=1&__d=dis) >>>

Username: dermalink.official, Hashtag: skincareroutine, Followers: 5849

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sabas_origin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sabas_origin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sabas_origin/?__a=1&__d=dis) >>>

Username: sabas_origin, Hashtag: skincareroutine, Followers: 1520

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/abeclasui.id/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/abeclasui.id/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/abeclasui.id/?__a=1&__d=dis) >>>

Username: abeclasui.id, Hashtag: skincareroutine, Followers: 8348

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/eldorasueolshop/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/eldorasueolshop/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/eldorasueolshop/?__a=1&__d=dis) >>>

Username: eldorasueolshop, Hashtag: skincareroutine, Followers: 1036

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/fefeglamour/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/fefeglamour/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/fefeglamour/?__a=1&__d=dis) >>>

Username: fefeglamour, Hashtag: skincareroutine, Followers: 62

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sarahli74/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sarahli74/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sarahli74/?__a=1&__d=dis) >>>

Username: sarahli74, Hashtag: skincareroutine, Followers: 9

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayutvak/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayutvak/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayutvak/?__a=1&__d=dis) >>>

Username: ayutvak, Hashtag: skincareroutine, Followers: 68

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drkalpana_renewskinclinic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drkalpana_renewskinclinic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drkalpana_renewskinclinic/?__a=1&__d=dis) >>>

Username: drkalpana_renewskinclinic, Hashtag: skincareroutine, Followers: 1786

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/myskincarejourney.t/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/myskincarejourney.t/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/myskincarejourney.t/?__a=1&__d=dis) >>>

Username: myskincarejourney.t, Hashtag: skincareroutine, Followers: 0

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/athmanwellnesscentervijaynagar/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/athmanwellnesscentervijaynagar/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/athmanwellnesscentervijaynagar/?__a=1&__d=dis) >>>

Username: athmanwellnesscentervijaynagar, Hashtag: skincareroutine, Followers: 128

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinandfertilityinstitute/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinandfertilityinstitute/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinandfertilityinstitute/?__a=1&__d=dis) >>>

Username: skinandfertilityinstitute, Hashtag: skincareroutine, Followers: 295

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/adgrohairandgloskinkokapet/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/adgrohairandgloskinkokapet/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/adgrohairandgloskinkokapet/?__a=1&__d=dis) >>>

Username: adgrohairandgloskinkokapet, Hashtag: skincareroutine, Followers: 655

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kjserums/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kjserums/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kjserums/?__a=1&__d=dis) >>>

Username: kjserums, Hashtag: skincareroutine, Followers: 13036

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jennysabrina16/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jennysabrina16/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jennysabrina16/?__a=1&__d=dis) >>>

Username: jennysabrina16, Hashtag: skincareroutine, Followers: 1803

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyscaraa/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyscaraa/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyscaraa/?__a=1&__d=dis) >>>

Username: beautyscaraa, Hashtag: skincareroutine, Followers: 205418

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lakmeacademypimpri_official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lakmeacademypimpri_official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lakmeacademypimpri_official/?__a=1&__d=dis) >>>

Username: lakmeacademypimpri_official, Hashtag: skincareroutine, Followers: 547

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowupyou_bd/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowupyou_bd/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowupyou_bd/?__a=1&__d=dis) >>>

Username: glowupyou_bd, Hashtag: skincareroutine, Followers: 4

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_skinerby/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_skinerby/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_skinerby/?__a=1&__d=dis) >>>

Username: _skinerby, Hashtag: skincareroutine, Followers: 2142

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin.dr.amisha/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin.dr.amisha/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin.dr.amisha/?__a=1&__d=dis) >>>

Username: skin.dr.amisha, Hashtag: skincareroutine, Followers: 1301

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/adonis_beauty_studio/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/adonis_beauty_studio/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/adonis_beauty_studio/?__a=1&__d=dis) >>>

Username: adonis_beauty_studio, Hashtag: skincareroutine, Followers: 1129

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glizbeautee/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glizbeautee/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glizbeautee/?__a=1&__d=dis) >>>

Username: glizbeautee, Hashtag: skincareroutine, Followers: 51791

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/foxybeautyza/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/foxybeautyza/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/foxybeautyza/?__a=1&__d=dis) >>>

Username: foxybeautyza, Hashtag: skincareroutine, Followers: 432

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/marfskinbeautyofficial/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/marfskinbeautyofficial/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/marfskinbeautyofficial/?__a=1&__d=dis) >>>

Username: marfskinbeautyofficial, Hashtag: skincareroutine, Followers: 20112

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/blonde.kj/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/blonde.kj/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/blonde.kj/?__a=1&__d=dis) >>>

Username: blonde.kj, Hashtag: skincareroutine, Followers: 612

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elixora_by_jm/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elixora_by_jm/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elixora_by_jm/?__a=1&__d=dis) >>>

Username: elixora_by_jm, Hashtag: skincareroutine, Followers: 3

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cedarandsage.co/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cedarandsage.co/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cedarandsage.co/?__a=1&__d=dis) >>>

Username: cedarandsage.co, Hashtag: skincareroutine, Followers: 5

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tl_skintherapy/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tl_skintherapy/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tl_skintherapy/?__a=1&__d=dis) >>>

Username: tl_skintherapy, Hashtag: skincareroutine, Followers: 311

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/aksharskinandhairclinic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/aksharskinandhairclinic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/aksharskinandhairclinic/?__a=1&__d=dis) >>>

Username: aksharskinandhairclinic, Hashtag: skincareroutine, Followers: 265

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/primadonaskincare.sby/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/primadonaskincare.sby/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/primadonaskincare.sby/?__a=1&__d=dis) >>>

Username: primadonaskincare.sby, Hashtag: skincareroutine, Followers: 78

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/triolab.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/triolab.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/triolab.in/?__a=1&__d=dis) >>>

Username: triolab.in, Hashtag: skincareroutine, Followers: 180

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facebodyandsoulaustralia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facebodyandsoulaustralia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facebodyandsoulaustralia/?__a=1&__d=dis) >>>

Username: facebodyandsoulaustralia, Hashtag: skincareroutine, Followers: 736

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowupwtips07/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowupwtips07/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowupwtips07/?__a=1&__d=dis) >>>

Username: glowupwtips07, Hashtag: skincareroutine, Followers: 22

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/trendz_studio_pune/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/trendz_studio_pune/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/trendz_studio_pune/?__a=1&__d=dis) >>>

Username: trendz_studio_pune, Hashtag: skincareroutine, Followers: 8188

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/orogold_ph/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/orogold_ph/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/orogold_ph/?__a=1&__d=dis) >>>

Username: orogold_ph, Hashtag: skincareroutine, Followers: 8805

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/hebebeautyconcept/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/hebebeautyconcept/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/hebebeautyconcept/?__a=1&__d=dis) >>>

Username: hebebeautyconcept, Hashtag: skincareroutine, Followers: 444

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elisabeth.schwarz.50/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elisabeth.schwarz.50/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elisabeth.schwarz.50/?__a=1&__d=dis) >>>

Username: elisabeth.schwarz.50, Hashtag: skincareroutine, Followers: 131

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ordinarybd.shop/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ordinarybd.shop/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ordinarybd.shop/?__a=1&__d=dis) >>>

Username: ordinarybd.shop, Hashtag: skincareroutine, Followers: 0

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinismbydr.shanza/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinismbydr.shanza/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinismbydr.shanza/?__a=1&__d=dis) >>>

Username: skinismbydr.shanza, Hashtag: skincareroutine, Followers: 1483

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.zanealam_health_tips/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.zanealam_health_tips/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.zanealam_health_tips/?__a=1&__d=dis) >>>

Username: dr.zanealam_health_tips, Hashtag: skincareroutine, Followers: 2342

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/official.goongbe_us/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/official.goongbe_us/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/official.goongbe_us/?__a=1&__d=dis) >>>

Username: official.goongbe_us, Hashtag: skincareroutine, Followers: 5377

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/neateveryday/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/neateveryday/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/neateveryday/?__a=1&__d=dis) >>>

Username: neateveryday, Hashtag: skincareroutine, Followers: 93

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/devantiskincare.jakarta/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/devantiskincare.jakarta/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/devantiskincare.jakarta/?__a=1&__d=dis) >>>

Username: devantiskincare.jakarta, Hashtag: skincareroutine, Followers: 9814

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cosmatics.quetta/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cosmatics.quetta/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cosmatics.quetta/?__a=1&__d=dis) >>>

Username: cosmatics.quetta, Hashtag: skincareroutine, Followers: 5

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nutriorient9/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nutriorient9/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nutriorient9/?__a=1&__d=dis) >>>

Username: nutriorient9, Hashtag: skincareroutine, Followers: 142

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/natures_nurture_spa_and_beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/natures_nurture_spa_and_beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/natures_nurture_spa_and_beauty/?__a=1&__d=dis) >>>

Username: natures_nurture_spa_and_beauty, Hashtag: skincareroutine, Followers: 163

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/amandeep.fitcoach/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/amandeep.fitcoach/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/amandeep.fitcoach/?__a=1&__d=dis) >>>

Username: amandeep.fitcoach, Hashtag: skincareroutine, Followers: 142

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/calmcollective_zoe/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/calmcollective_zoe/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/calmcollective_zoe/?__a=1&__d=dis) >>>

Username: calmcollective_zoe, Hashtag: skincareroutine, Followers: 1107

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/allbouttheglow.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/allbouttheglow.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/allbouttheglow.in/?__a=1&__d=dis) >>>

Username: allbouttheglow.in, Hashtag: indianskincareroutine, Followers: 48

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bitaminnaturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bitaminnaturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bitaminnaturals/?__a=1&__d=dis) >>>

Username: bitaminnaturals, Hashtag: indianskincareroutine, Followers: 5141

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sukha.veda/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sukha.veda/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sukha.veda/?__a=1&__d=dis) >>>

Username: sukha.veda, Hashtag: indianskincareroutine, Followers: 1186

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dhikashnaturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dhikashnaturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dhikashnaturals/?__a=1&__d=dis) >>>

Username: dhikashnaturals, Hashtag: indianskincareroutine, Followers: 1801

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty__glamzz/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty__glamzz/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty__glamzz/?__a=1&__d=dis) >>>

Username: beauty__glamzz, Hashtag: indianskincareroutine, Followers: 483

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/loveyourskintone/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/loveyourskintone/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/loveyourskintone/?__a=1&__d=dis) >>>

Username: loveyourskintone, Hashtag: indianskincareroutine, Followers: 1437

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glam_soul_11/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glam_soul_11/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glam_soul_11/?__a=1&__d=dis) >>>

Username: glam_soul_11, Hashtag: indianskincareroutine, Followers: 1187

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_skin_story_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_skin_story_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_skin_story_/?__a=1&__d=dis) >>>

Username: the_skin_story_, Hashtag: indianskincareroutine, Followers: 19

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/umarahorganics/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/umarahorganics/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/umarahorganics/?__a=1&__d=dis) >>>

Username: umarahorganics, Hashtag: indianskincareroutine, Followers: 31

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/roopsons_stores/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/roopsons_stores/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/roopsons_stores/?__a=1&__d=dis) >>>

Username: roopsons_stores, Hashtag: indianskincareroutine, Followers: 421

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty_carezz/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty_carezz/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty_carezz/?__a=1&__d=dis) >>>

Username: beauty_carezz, Hashtag: indianskincareroutine, Followers: 510

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcarebyprem/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcarebyprem/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcarebyprem/?__a=1&__d=dis) >>>

Username: selfcarebyprem, Hashtag: indianskincareroutine, Followers: 56259

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tanvirawal/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tanvirawal/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tanvirawal/?__a=1&__d=dis) >>>

Username: tanvirawal, Hashtag: indianskincareroutine, Followers: 19509

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/forestmama_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/forestmama_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/forestmama_skincare/?__a=1&__d=dis) >>>

Username: forestmama_skincare, Hashtag: indianskincareroutine, Followers: 2986

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/minal__beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/minal__beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/minal__beauty/?__a=1&__d=dis) >>>
Status 404: Endpoint /v1/users/minal__beauty/usernameinfo/ does not exist

❌ Error fetching data for minal__beauty: User not found

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ardranaturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ardranaturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ardranaturals/?__a=1&__d=dis) >>>

Username: ardranaturals, Hashtag: indianskincareroutine, Followers: 1068

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/melanomagasimane8/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/melanomagasimane8/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/melanomagasimane8/?__a=1&__d=dis) >>>

Username: melanomagasimane8, Hashtag: indianskincareroutine, Followers: 1627

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.glazed_donut/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.glazed_donut/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.glazed_donut/?__a=1&__d=dis) >>>

Username: dr.glazed_donut, Hashtag: indianskincareroutine, Followers: 429

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/necessaryindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/necessaryindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/necessaryindia/?__a=1&__d=dis) >>>

Username: necessaryindia, Hashtag: indianskincareroutine, Followers: 7283

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/simplybeautifulss/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/simplybeautifulss/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/simplybeautifulss/?__a=1&__d=dis) >>>

Username: simplybeautifulss, Hashtag: indianskincareroutine, Followers: 622

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sunshine.001__/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sunshine.001__/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sunshine.001__/?__a=1&__d=dis) >>>

Username: sunshine.001__, Hashtag: indianskincareroutine, Followers: 2271

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/vivalabella.co.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/vivalabella.co.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/vivalabella.co.in/?__a=1&__d=dis) >>>

Username: vivalabella.co.in, Hashtag: indianskincareroutine, Followers: 62

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lixa_skin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lixa_skin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lixa_skin/?__a=1&__d=dis) >>>

Username: lixa_skin, Hashtag: indianskincareroutine, Followers: 232

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shajasorganics/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shajasorganics/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shajasorganics/?__a=1&__d=dis) >>>

Username: shajasorganics, Hashtag: indianskincareroutine, Followers: 3877

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beskskin_with_bosky/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beskskin_with_bosky/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beskskin_with_bosky/?__a=1&__d=dis) >>>

Username: beskskin_with_bosky, Hashtag: indianskincareroutine, Followers: 26

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ugcwitharya/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ugcwitharya/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ugcwitharya/?__a=1&__d=dis) >>>

Username: ugcwitharya, Hashtag: indianskincareroutine, Followers: 109

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/4myspacealone/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/4myspacealone/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/4myspacealone/?__a=1&__d=dis) >>>

Username: 4myspacealone, Hashtag: indianskincareroutine, Followers: 148

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/khwaish_rijhwani/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/khwaish_rijhwani/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/khwaish_rijhwani/?__a=1&__d=dis) >>>

Username: khwaish_rijhwani, Hashtag: indianskincareroutine, Followers: 9481

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drmadhuakhourichopra/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drmadhuakhourichopra/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drmadhuakhourichopra/?__a=1&__d=dis) >>>

Username: drmadhuakhourichopra, Hashtag: indianskincareroutine, Followers: 122303

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/pinchofsalo/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/pinchofsalo/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/pinchofsalo/?__a=1&__d=dis) >>>

Username: pinchofsalo, Hashtag: indianskincareroutine, Followers: 1269

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/idoskincarebutmyskindoesntcare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/idoskincarebutmyskindoesntcare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/idoskincarebutmyskindoesntcare/?__a=1&__d=dis) >>>

Username: idoskincarebutmyskindoesntcare, Hashtag: indianskincareroutine, Followers: 194

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinsecs/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinsecs/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinsecs/?__a=1&__d=dis) >>>

Username: skinsecs, Hashtag: indianskincareroutine, Followers: 6946

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/merakibeauty.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/merakibeauty.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/merakibeauty.in/?__a=1&__d=dis) >>>

Username: merakibeauty.in, Hashtag: indianskincareroutine, Followers: 5518

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_with_gg/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_with_gg/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_with_gg/?__a=1&__d=dis) >>>

Username: skincare_with_gg, Hashtag: indianskincareroutine, Followers: 2582

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shynreddy/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shynreddy/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shynreddy/?__a=1&__d=dis) >>>

Username: shynreddy, Hashtag: indianskincareroutine, Followers: 15071

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/vridhi.balwani/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/vridhi.balwani/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/vridhi.balwani/?__a=1&__d=dis) >>>

Username: vridhi.balwani, Hashtag: indianskincareroutine, Followers: 1822

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elegance_beauty4u/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elegance_beauty4u/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elegance_beauty4u/?__a=1&__d=dis) >>>

Username: elegance_beauty4u, Hashtag: indianskincareroutine, Followers: 10134

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowjunkieblog/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowjunkieblog/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowjunkieblog/?__a=1&__d=dis) >>>

Username: glowjunkieblog, Hashtag: indianskincareroutine, Followers: 3940

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/diaaugc/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/diaaugc/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/diaaugc/?__a=1&__d=dis) >>>

Username: diaaugc, Hashtag: indianskincareroutine, Followers: 1029

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chicandluminous/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chicandluminous/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chicandluminous/?__a=1&__d=dis) >>>

Username: chicandluminous, Hashtag: indianskincareroutine, Followers: 0

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincaresiblingss/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincaresiblingss/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincaresiblingss/?__a=1&__d=dis) >>>

Username: skincaresiblingss, Hashtag: indianskincareroutine, Followers: 49

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/entan_gledlove/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/entan_gledlove/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/entan_gledlove/?__a=1&__d=dis) >>>

Username: entan_gledlove, Hashtag: indianskincareroutine, Followers: 638

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/prakritibacktonature/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/prakritibacktonature/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/prakritibacktonature/?__a=1&__d=dis) >>>

Username: prakritibacktonature, Hashtag: indianskincareroutine, Followers: 1061

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty_tech_care/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty_tech_care/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beauty_tech_care/?__a=1&__d=dis) >>>

Username: beauty_tech_care, Hashtag: indianskincareroutine, Followers: 10317

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/klairs.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/klairs.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/klairs.in/?__a=1&__d=dis) >>>

Username: klairs.in, Hashtag: indianskincareroutine, Followers: 15431

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/celestiskin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/celestiskin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/celestiskin/?__a=1&__d=dis) >>>

Username: celestiskin, Hashtag: indianskincareroutine, Followers: 1598

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thesundaysuppers/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thesundaysuppers/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thesundaysuppers/?__a=1&__d=dis) >>>

Username: thesundaysuppers, Hashtag: indianskincareroutine, Followers: 63926

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/himabindu_avula__/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/himabindu_avula__/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/himabindu_avula__/?__a=1&__d=dis) >>>

Username: himabindu_avula__, Hashtag: indianskincareroutine, Followers: 23307

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chicelegancexo/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chicelegancexo/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chicelegancexo/?__a=1&__d=dis) >>>

Username: chicelegancexo, Hashtag: indianskincareroutine, Followers: 3

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin.nbeyond/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin.nbeyond/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin.nbeyond/?__a=1&__d=dis) >>>

Username: skin.nbeyond, Hashtag: indianskincareroutine, Followers: 1547

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/withlalitha/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/withlalitha/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/withlalitha/?__a=1&__d=dis) >>>

Username: withlalitha, Hashtag: indianskincareroutine, Followers: 539

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/iampreciossa/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/iampreciossa/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/iampreciossa/?__a=1&__d=dis) >>>

Username: iampreciossa, Hashtag: indianskincareroutine, Followers: 993

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincareselfcaree/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincareselfcaree/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincareselfcaree/?__a=1&__d=dis) >>>

Username: skincareselfcaree, Hashtag: indianskincareroutine, Followers: 101

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinnneticc/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinnneticc/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinnneticc/?__a=1&__d=dis) >>>

Username: skinnneticc, Hashtag: indianskincareroutine, Followers: 28158

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautywith_wendy_mizo/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautywith_wendy_mizo/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautywith_wendy_mizo/?__a=1&__d=dis) >>>

Username: beautywith_wendy_mizo, Hashtag: indianskincareroutine, Followers: 3990

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin_glamz/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin_glamz/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skin_glamz/?__a=1&__d=dis) >>>

Username: skin_glamz, Hashtag: indianskincareroutine, Followers: 2139

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/veda_harvest/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/veda_harvest/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/veda_harvest/?__a=1&__d=dis) >>>

Username: veda_harvest, Hashtag: indianskincareroutine, Followers: 12806

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/atulyaofficial/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/atulyaofficial/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/atulyaofficial/?__a=1&__d=dis) >>>

Username: atulyaofficial, Hashtag: indianskincareroutine, Followers: 29825

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinfinitytales/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinfinitytales/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinfinitytales/?__a=1&__d=dis) >>>

Username: theskinfinitytales, Hashtag: indianskincareroutine, Followers: 256

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/limese_connect/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/limese_connect/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/limese_connect/?__a=1&__d=dis) >>>

Username: limese_connect, Hashtag: indianskincareroutine, Followers: 39248

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theformularx/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theformularx/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theformularx/?__a=1&__d=dis) >>>

Username: theformularx, Hashtag: indianskincareroutine, Followers: 47111

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinlumina_kannada/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinlumina_kannada/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinlumina_kannada/?__a=1&__d=dis) >>>

Username: skinlumina_kannada, Hashtag: indianskincareroutine, Followers: 617

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ruhaani_skincare_india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ruhaani_skincare_india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ruhaani_skincare_india/?__a=1&__d=dis) >>>

Username: ruhaani_skincare_india, Hashtag: indianskincareroutine, Followers: 643

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glambeautyjournnal/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glambeautyjournnal/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glambeautyjournnal/?__a=1&__d=dis) >>>

Username: glambeautyjournnal, Hashtag: indianskincareroutine, Followers: 3387

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tropiglow.beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tropiglow.beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tropiglow.beauty/?__a=1&__d=dis) >>>

Username: tropiglow.beauty, Hashtag: indianskincareroutine, Followers: 2555

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/earthybyellenza/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/earthybyellenza/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/earthybyellenza/?__a=1&__d=dis) >>>

Username: earthybyellenza, Hashtag: indianskincareroutine, Followers: 52617

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thatglowsecret/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thatglowsecret/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thatglowsecret/?__a=1&__d=dis) >>>

Username: thatglowsecret, Hashtag: indianskincareroutine, Followers: 32

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/juneskyn/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/juneskyn/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/juneskyn/?__a=1&__d=dis) >>>

Username: juneskyn, Hashtag: indianskincareroutine, Followers: 303

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/moh_balancedskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/moh_balancedskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/moh_balancedskincare/?__a=1&__d=dis) >>>

Username: moh_balancedskincare, Hashtag: indianskincareroutine, Followers: 431

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/panning_journal/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/panning_journal/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/panning_journal/?__a=1&__d=dis) >>>

Username: panning_journal, Hashtag: indianskincareroutine, Followers: 607

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/asapmedical/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/asapmedical/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/asapmedical/?__a=1&__d=dis) >>>

Username: asapmedical, Hashtag: indianskincareroutine, Followers: 4567

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/review_with_ann_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/review_with_ann_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/review_with_ann_/?__a=1&__d=dis) >>>

Username: review_with_ann_, Hashtag: indianskincareroutine, Followers: 7

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskincare.cafe/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskincare.cafe/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskincare.cafe/?__a=1&__d=dis) >>>

Username: theskincare.cafe, Hashtag: indianskincareroutine, Followers: 418

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tikitoroindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tikitoroindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tikitoroindia/?__a=1&__d=dis) >>>

Username: tikitoroindia, Hashtag: indianskincareroutine, Followers: 21999

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/erikkaindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/erikkaindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/erikkaindia/?__a=1&__d=dis) >>>

Username: erikkaindia, Hashtag: indianskincareroutine, Followers: 8023

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarez7778/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarez7778/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarez7778/?__a=1&__d=dis) >>>

Username: skincarez7778, Hashtag: indianskincareroutine, Followers: 5816

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/darshiina/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/darshiina/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/darshiina/?__a=1&__d=dis) >>>

Username: darshiina, Hashtag: indianskincareroutine, Followers: 120086

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/phalgunisarkar_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/phalgunisarkar_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/phalgunisarkar_/?__a=1&__d=dis) >>>

Username: phalgunisarkar_, Hashtag: indianskincareroutine, Followers: 112

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/unsweetened.beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/unsweetened.beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/unsweetened.beauty/?__a=1&__d=dis) >>>

Username: unsweetened.beauty, Hashtag: indianskincareroutine, Followers: 36625

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dalba_india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dalba_india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dalba_india/?__a=1&__d=dis) >>>

Username: dalba_india, Hashtag: indianskincareroutine, Followers: 1496

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kavitadhandhariabubna/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kavitadhandhariabubna/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kavitadhandhariabubna/?__a=1&__d=dis) >>>

Username: kavitadhandhariabubna, Hashtag: indianskincareroutine, Followers: 1033

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yittalite/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yittalite/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yittalite/?__a=1&__d=dis) >>>

Username: yittalite, Hashtag: indianskincareroutine, Followers: 4994

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yourdailyskincare1/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yourdailyskincare1/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yourdailyskincare1/?__a=1&__d=dis) >>>

Username: yourdailyskincare1, Hashtag: indianskincareroutine, Followers: 0

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/deep_love_skin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/deep_love_skin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/deep_love_skin/?__a=1&__d=dis) >>>

Username: deep_love_skin, Hashtag: indianskincareroutine, Followers: 494

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcare.istasha/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcare.istasha/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcare.istasha/?__a=1&__d=dis) >>>

Username: selfcare.istasha, Hashtag: indianskincareroutine, Followers: 4183

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facen_beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facen_beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facen_beauty/?__a=1&__d=dis) >>>

Username: facen_beauty, Hashtag: indianskincareroutine, Followers: 1417

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/fsascares/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/fsascares/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/fsascares/?__a=1&__d=dis) >>>

Username: fsascares, Hashtag: indianskincareroutine, Followers: 10396

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bloomshine.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bloomshine.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bloomshine.in/?__a=1&__d=dis) >>>

Username: bloomshine.in, Hashtag: indianskincareroutine, Followers: 156

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yourskincarefrnd/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yourskincarefrnd/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yourskincarefrnd/?__a=1&__d=dis) >>>

Username: yourskincarefrnd, Hashtag: indianskincareroutine, Followers: 1423

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarezio/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarezio/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarezio/?__a=1&__d=dis) >>>

Username: skincarezio, Hashtag: indianskincareroutine, Followers: 1162

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/oneof.india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/oneof.india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/oneof.india/?__a=1&__d=dis) >>>

Username: oneof.india, Hashtag: indianskincareroutine, Followers: 436

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lovelocalindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lovelocalindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lovelocalindia/?__a=1&__d=dis) >>>

Username: lovelocalindia, Hashtag: indianskincareroutine, Followers: 9344

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/svarasyaindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/svarasyaindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/svarasyaindia/?__a=1&__d=dis) >>>

Username: svarasyaindia, Hashtag: indianskincareroutine, Followers: 14299

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/enhance_allure_skin_aesthetics/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/enhance_allure_skin_aesthetics/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/enhance_allure_skin_aesthetics/?__a=1&__d=dis) >>>

Username: enhance_allure_skin_aesthetics, Hashtag: indianskincareroutine, Followers: 132

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drcosmoglow/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drcosmoglow/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drcosmoglow/?__a=1&__d=dis) >>>

Username: drcosmoglow, Hashtag: indianskincareroutine, Followers: 3067

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elle.with.care/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elle.with.care/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/elle.with.care/?__a=1&__d=dis) >>>

Username: elle.with.care, Hashtag: indianskincareroutine, Followers: 14

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayuryugaofficial/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayuryugaofficial/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ayuryugaofficial/?__a=1&__d=dis) >>>

Username: ayuryugaofficial, Hashtag: indianskincareroutine, Followers: 7928

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/white.slate/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/white.slate/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/white.slate/?__a=1&__d=dis) >>>

Username: white.slate, Hashtag: indianskincareroutine, Followers: 1606

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shsmi_estheticcenter/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shsmi_estheticcenter/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shsmi_estheticcenter/?__a=1&__d=dis) >>>

Username: shsmi_estheticcenter, Hashtag: indianskincareroutine, Followers: 65

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drkatheejanasika/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drkatheejanasika/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drkatheejanasika/?__a=1&__d=dis) >>>

Username: drkatheejanasika, Hashtag: indianskincareroutine, Followers: 2043

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/just.vediiii.things/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/just.vediiii.things/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/just.vediiii.things/?__a=1&__d=dis) >>>

Username: just.vediiii.things, Hashtag: indianskincareroutine, Followers: 1669

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/secret_indiaa/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/secret_indiaa/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/secret_indiaa/?__a=1&__d=dis) >>>

Username: secret_indiaa, Hashtag: indianskincareroutine, Followers: 169

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/crypto_hackerr/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/crypto_hackerr/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/crypto_hackerr/?__a=1&__d=dis) >>>

Username: crypto_hackerr, Hashtag: indianskincareroutine, Followers: 18337

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/missstiii29/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/missstiii29/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/missstiii29/?__a=1&__d=dis) >>>

Username: missstiii29, Hashtag: indianskincareroutine, Followers: 1898

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinocharm_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinocharm_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinocharm_/?__a=1&__d=dis) >>>

Username: skinocharm_, Hashtag: indianskincareroutine, Followers: 5783

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinyogi_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinyogi_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinyogi_/?__a=1&__d=dis) >>>

Username: theskinyogi_, Hashtag: indianskincareroutine, Followers: 552

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tyc.theyujchapter/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tyc.theyujchapter/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tyc.theyujchapter/?__a=1&__d=dis) >>>

Username: tyc.theyujchapter, Hashtag: indianskincareroutine, Followers: 830

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/rechargeyourskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/rechargeyourskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/rechargeyourskincare/?__a=1&__d=dis) >>>

Username: rechargeyourskincare, Hashtag: indianskincareroutine, Followers: 2290

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/emartbd.official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/emartbd.official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/emartbd.official/?__a=1&__d=dis) >>>

Username: emartbd.official, Hashtag: indianskincareroutine, Followers: 3585

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glossyglowup_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glossyglowup_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glossyglowup_/?__a=1&__d=dis) >>>

Username: glossyglowup_, Hashtag: indianskincareroutine, Followers: 15

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinstudiobyras/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinstudiobyras/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinstudiobyras/?__a=1&__d=dis) >>>

Username: skinstudiobyras, Hashtag: indianskincareroutine, Followers: 8262

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thedewyskinmarine/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thedewyskinmarine/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thedewyskinmarine/?__a=1&__d=dis) >>>

Username: thedewyskinmarine, Hashtag: indianskincareroutine, Followers: 13941

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_activealchemy_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_activealchemy_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_activealchemy_/?__a=1&__d=dis) >>>

Username: _activealchemy_, Hashtag: indianskincareroutine, Followers: 1

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_sunkissed_fashionista/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_sunkissed_fashionista/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_sunkissed_fashionista/?__a=1&__d=dis) >>>

Username: the_sunkissed_fashionista, Hashtag: indianskincareroutine, Followers: 6085

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/avaniskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/avaniskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/avaniskincare/?__a=1&__d=dis) >>>

Username: avaniskincare, Hashtag: indianskincareroutine, Followers: 2356

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/surreal_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/surreal_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/surreal_skincare/?__a=1&__d=dis) >>>

Username: surreal_skincare, Hashtag: indianskincareroutine, Followers: 620

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinn_point/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinn_point/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinn_point/?__a=1&__d=dis) >>>

Username: skinn_point, Hashtag: indianskincareroutine, Followers: 27

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lifeofme_astt/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lifeofme_astt/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lifeofme_astt/?__a=1&__d=dis) >>>

Username: lifeofme_astt, Hashtag: indianskincareroutine, Followers: 1783

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sofiashakirmua/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sofiashakirmua/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sofiashakirmua/?__a=1&__d=dis) >>>

Username: sofiashakirmua, Hashtag: indianskincareroutine, Followers: 5113

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/naf.on.derm/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/naf.on.derm/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/naf.on.derm/?__a=1&__d=dis) >>>

Username: naf.on.derm, Hashtag: indianskincareroutine, Followers: 8927

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kefibeautyindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kefibeautyindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kefibeautyindia/?__a=1&__d=dis) >>>

Username: kefibeautyindia, Hashtag: indianskincareroutine, Followers: 1294

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinlovenirali/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinlovenirali/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinlovenirali/?__a=1&__d=dis) >>>

Username: skinlovenirali, Hashtag: indianskincareroutine, Followers: 1301

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincareeuphoria_in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincareeuphoria_in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincareeuphoria_in/?__a=1&__d=dis) >>>

Username: skincareeuphoria_in, Hashtag: indianskincareroutine, Followers: 532

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/anushrijain20/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/anushrijain20/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/anushrijain20/?__a=1&__d=dis) >>>

Username: anushrijain20, Hashtag: indianskincareroutine, Followers: 8395

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.komal_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.komal_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.komal_skincare/?__a=1&__d=dis) >>>

Username: dr.komal_skincare, Hashtag: indianskincareroutine, Followers: 2324

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shraddha_photo_world/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shraddha_photo_world/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shraddha_photo_world/?__a=1&__d=dis) >>>

Username: shraddha_photo_world, Hashtag: indianskincareroutine, Followers: 53

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/all.glam.guide/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/all.glam.guide/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/all.glam.guide/?__a=1&__d=dis) >>>

Username: all.glam.guide, Hashtag: indianskincareroutine, Followers: 1657

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/groomlybd/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/groomlybd/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/groomlybd/?__a=1&__d=dis) >>>

Username: groomlybd, Hashtag: indianskincareroutine, Followers: 2535

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thinkskinclinic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thinkskinclinic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thinkskinclinic/?__a=1&__d=dis) >>>

Username: thinkskinclinic, Hashtag: indianskincareroutine, Followers: 642

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/healwith.her/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/healwith.her/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/healwith.her/?__a=1&__d=dis) >>>

Username: healwith.her, Hashtag: indianskincareroutine, Followers: 152

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mizo.skincare.enthusiast/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mizo.skincare.enthusiast/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mizo.skincare.enthusiast/?__a=1&__d=dis) >>>

Username: mizo.skincare.enthusiast, Hashtag: indianskincareroutine, Followers: 17948

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_diaries_want/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_diaries_want/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_diaries_want/?__a=1&__d=dis) >>>

Username: skincare_diaries_want, Hashtag: indianskincareroutine, Followers: 15

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dreamyvision19/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dreamyvision19/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dreamyvision19/?__a=1&__d=dis) >>>

Username: dreamyvision19, Hashtag: indianskincareroutine, Followers: 472

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/essential_stuffz/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/essential_stuffz/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/essential_stuffz/?__a=1&__d=dis) >>>

Username: essential_stuffz, Hashtag: indianskincareroutine, Followers: 50

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nisvaskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nisvaskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nisvaskincare/?__a=1&__d=dis) >>>

Username: nisvaskincare, Hashtag: indianskincareroutine, Followers: 240

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcarebymeghna/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcarebymeghna/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/selfcarebymeghna/?__a=1&__d=dis) >>>

Username: selfcarebymeghna, Hashtag: indianskincareroutine, Followers: 72

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glow_with_hem/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glow_with_hem/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glow_with_hem/?__a=1&__d=dis) >>>

Username: glow_with_hem, Hashtag: indianskincareroutine, Followers: 137

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/luna_bay_shoppe/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/luna_bay_shoppe/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/luna_bay_shoppe/?__a=1&__d=dis) >>>

Username: luna_bay_shoppe, Hashtag: indianskincareroutine, Followers: 499

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/rejithanandini/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/rejithanandini/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/rejithanandini/?__a=1&__d=dis) >>>

Username: rejithanandini, Hashtag: indianskincareroutine, Followers: 596

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_beauty_tips_1207/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_beauty_tips_1207/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_beauty_tips_1207/?__a=1&__d=dis) >>>

Username: _beauty_tips_1207, Hashtag: indianskincareroutine, Followers: 4

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dewydisposition/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dewydisposition/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dewydisposition/?__a=1&__d=dis) >>>

Username: dewydisposition, Hashtag: indianskincareroutine, Followers: 46622

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nikki.pans/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nikki.pans/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nikki.pans/?__a=1&__d=dis) >>>

Username: nikki.pans, Hashtag: indianskincareroutine, Followers: 207

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shop.wellwell/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shop.wellwell/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shop.wellwell/?__a=1&__d=dis) >>>

Username: shop.wellwell, Hashtag: indianskincareroutine, Followers: 4645

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sujatasharma06/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sujatasharma06/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sujatasharma06/?__a=1&__d=dis) >>>

Username: sujatasharma06, Hashtag: indianskincareroutine, Followers: 16499

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cneudbasic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cneudbasic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cneudbasic/?__a=1&__d=dis) >>>

Username: cneudbasic, Hashtag: indianskincareroutine, Followers: 16222

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/basicbeautyblogs/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/basicbeautyblogs/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/basicbeautyblogs/?__a=1&__d=dis) >>>

Username: basicbeautyblogs, Hashtag: indianskincareroutine, Followers: 48

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/flawless_magicc/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/flawless_magicc/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/flawless_magicc/?__a=1&__d=dis) >>>

Username: flawless_magicc, Hashtag: indianskincareroutine, Followers: 1975

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jennys_arabian_beauty_hq/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jennys_arabian_beauty_hq/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/jennys_arabian_beauty_hq/?__a=1&__d=dis) >>>

Username: jennys_arabian_beauty_hq, Hashtag: indianskincareroutine, Followers: 1830

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.samujjala_inskin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.samujjala_inskin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr.samujjala_inskin/?__a=1&__d=dis) >>>

Username: dr.samujjala_inskin, Hashtag: indianskincareroutine, Followers: 21979

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare6668/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare6668/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare6668/?__a=1&__d=dis) >>>

Username: skincare6668, Hashtag: indianskincareroutine, Followers: 50755

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinlanguage_official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinlanguage_official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/theskinlanguage_official/?__a=1&__d=dis) >>>

Username: theskinlanguage_official, Hashtag: indianskincareroutine, Followers: 723

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/reequil/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/reequil/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/reequil/?__a=1&__d=dis) >>>

Username: reequil, Hashtag: indianskincareroutine, Followers: 132575

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinpoetrybyashna/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinpoetrybyashna/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinpoetrybyashna/?__a=1&__d=dis) >>>

Username: skinpoetrybyashna, Hashtag: indianskincareroutine, Followers: 62

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/indiebae_in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/indiebae_in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/indiebae_in/?__a=1&__d=dis) >>>

Username: indiebae_in, Hashtag: indianskincareroutine, Followers: 7598

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_genix/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_genix/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare_genix/?__a=1&__d=dis) >>>

Username: skincare_genix, Hashtag: indianskincareroutine, Followers: 738

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/aradhanalucky2023/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/aradhanalucky2023/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/aradhanalucky2023/?__a=1&__d=dis) >>>

Username: aradhanalucky2023, Hashtag: indianskincareroutine, Followers: 1994

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/happyskinwithgouri/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/happyskinwithgouri/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/happyskinwithgouri/?__a=1&__d=dis) >>>

Username: happyskinwithgouri, Hashtag: indianskincareroutine, Followers: 25669

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drsadhanadeshmukh/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drsadhanadeshmukh/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/drsadhanadeshmukh/?__a=1&__d=dis) >>>

Username: drsadhanadeshmukh, Hashtag: indianskincareroutine, Followers: 22674

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_calm_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_calm_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_calm_skincare/?__a=1&__d=dis) >>>

Username: the_calm_skincare, Hashtag: indianskincareroutine, Followers: 999

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soulflowerindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soulflowerindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soulflowerindia/?__a=1&__d=dis) >>>

Username: soulflowerindia, Hashtag: indianskincareroutine, Followers: 212070

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ugcbysahana/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ugcbysahana/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ugcbysahana/?__a=1&__d=dis) >>>

Username: ugcbysahana, Hashtag: indianskincareroutine, Followers: 195

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nans.skin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nans.skin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/nans.skin/?__a=1&__d=dis) >>>

Username: nans.skin, Hashtag: indianskincareroutine, Followers: 578

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/natureinbottles2023/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/natureinbottles2023/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/natureinbottles2023/?__a=1&__d=dis) >>>

Username: natureinbottles2023, Hashtag: indianskincareroutine, Followers: 245

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/iba_cncs/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/iba_cncs/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/iba_cncs/?__a=1&__d=dis) >>>

Username: iba_cncs, Hashtag: indianskincareroutine, Followers: 2712

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/truffles_and_sunscreens/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/truffles_and_sunscreens/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/truffles_and_sunscreens/?__a=1&__d=dis) >>>

Username: truffles_and_sunscreens, Hashtag: indianskincareroutine, Followers: 510

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facestoriesbysiyamakeovers/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facestoriesbysiyamakeovers/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/facestoriesbysiyamakeovers/?__a=1&__d=dis) >>>

Username: facestoriesbysiyamakeovers, Hashtag: indianskincareroutine, Followers: 268

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mascotspincontrol/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mascotspincontrol/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mascotspincontrol/?__a=1&__d=dis) >>>

Username: mascotspincontrol, Hashtag: indianskincareroutine, Followers: 1721

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kskinbar/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kskinbar/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/kskinbar/?__a=1&__d=dis) >>>

Username: kskinbar, Hashtag: indianskincareroutine, Followers: 36017

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cerulean.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cerulean.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cerulean.in/?__a=1&__d=dis) >>>

Username: cerulean.in, Hashtag: indianskincareroutine, Followers: 3438

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/o4organic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/o4organic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/o4organic/?__a=1&__d=dis) >>>

Username: o4organic, Hashtag: indianskincareroutine, Followers: 131

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/peachyy_lemonade/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/peachyy_lemonade/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/peachyy_lemonade/?__a=1&__d=dis) >>>

Username: peachyy_lemonade, Hashtag: indianskincareroutine, Followers: 0

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dewydayss/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dewydayss/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dewydayss/?__a=1&__d=dis) >>>

Username: dewydayss, Hashtag: indianskincareroutine, Followers: 184

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thebeautythatinspire/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thebeautythatinspire/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/thebeautythatinspire/?__a=1&__d=dis) >>>

Username: thebeautythatinspire, Hashtag: indianskincareroutine, Followers: 20611

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yr_naturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yr_naturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yr_naturals/?__a=1&__d=dis) >>>

Username: yr_naturals, Hashtag: indianskincareroutine, Followers: 277

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/organikblends_bymona/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/organikblends_bymona/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/organikblends_bymona/?__a=1&__d=dis) >>>

Username: organikblends_bymona, Hashtag: indianskincareroutine, Followers: 689

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyy_secrets07/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyy_secrets07/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautyy_secrets07/?__a=1&__d=dis) >>>

Username: beautyy_secrets07, Hashtag: indianskincareroutine, Followers: 114

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lilcarebynandu/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lilcarebynandu/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/lilcarebynandu/?__a=1&__d=dis) >>>

Username: lilcarebynandu, Hashtag: indianskincareroutine, Followers: 1190

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/moonlyherb/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/moonlyherb/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/moonlyherb/?__a=1&__d=dis) >>>

Username: moonlyherb, Hashtag: indianskincareroutine, Followers: 1143

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/getinfopedia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/getinfopedia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/getinfopedia/?__a=1&__d=dis) >>>

Username: getinfopedia, Hashtag: indianskincareroutine, Followers: 596

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/m.a.d.skincareindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/m.a.d.skincareindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/m.a.d.skincareindia/?__a=1&__d=dis) >>>

Username: m.a.d.skincareindia, Hashtag: indianskincareroutine, Followers: 25

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/slesha_elza/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/slesha_elza/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/slesha_elza/?__a=1&__d=dis) >>>

Username: slesha_elza, Hashtag: indianskincareroutine, Followers: 1305

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/klive.young/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/klive.young/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/klive.young/?__a=1&__d=dis) >>>

Username: klive.young, Hashtag: indianskincareroutine, Followers: 0

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/my_daily_memoir/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/my_daily_memoir/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/my_daily_memoir/?__a=1&__d=dis) >>>

Username: my_daily_memoir, Hashtag: indianskincareroutine, Followers: 4

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sprinkledflavour/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sprinkledflavour/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/sprinkledflavour/?__a=1&__d=dis) >>>

Username: sprinkledflavour, Hashtag: indianskincareroutine, Followers: 5360

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soapcraftshubli/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soapcraftshubli/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soapcraftshubli/?__a=1&__d=dis) >>>

Username: soapcraftshubli, Hashtag: indianskincareroutine, Followers: 9609

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarebyprem/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarebyprem/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarebyprem/?__a=1&__d=dis) >>>

Username: skincarebyprem, Hashtag: indianskincareroutine, Followers: 24

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soapskart/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soapskart/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/soapskart/?__a=1&__d=dis) >>>

Username: soapskart, Hashtag: indianskincareroutine, Followers: 115114

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowwithkoni/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowwithkoni/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowwithkoni/?__a=1&__d=dis) >>>

Username: glowwithkoni, Hashtag: indianskincareroutine, Followers: 940

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr_dermagic_t/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr_dermagic_t/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dr_dermagic_t/?__a=1&__d=dis) >>>

Username: dr_dermagic_t, Hashtag: indianskincareroutine, Followers: 6013

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/girlyyskin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/girlyyskin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/girlyyskin/?__a=1&__d=dis) >>>

Username: girlyyskin, Hashtag: indianskincareroutine, Followers: 1070

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mumbai_uncensored/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mumbai_uncensored/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/mumbai_uncensored/?__a=1&__d=dis) >>>

Username: mumbai_uncensored, Hashtag: indianskincareroutine, Followers: 101399

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/banerjee.shreya_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/banerjee.shreya_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/banerjee.shreya_/?__a=1&__d=dis) >>>

Username: banerjee.shreya_, Hashtag: indianskincareroutine, Followers: 2112

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/oursserum/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/oursserum/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/oursserum/?__a=1&__d=dis) >>>

Username: oursserum, Hashtag: indianskincareroutine, Followers: 34

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/naturalbeautyaddict_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/naturalbeautyaddict_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/naturalbeautyaddict_/?__a=1&__d=dis) >>>

Username: naturalbeautyaddict_, Hashtag: indianskincareroutine, Followers: 2787

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/limese_offline/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/limese_offline/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/limese_offline/?__a=1&__d=dis) >>>

Username: limese_offline, Hashtag: indianskincareroutine, Followers: 640

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/heyskincare.india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/heyskincare.india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/heyskincare.india/?__a=1&__d=dis) >>>

Username: heyskincare.india, Hashtag: indianskincareroutine, Followers: 653

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/seoulbrendcosmetics/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/seoulbrendcosmetics/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/seoulbrendcosmetics/?__a=1&__d=dis) >>>

Username: seoulbrendcosmetics, Hashtag: indianskincareroutine, Followers: 298

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/trymefirst.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/trymefirst.in/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/trymefirst.in/?__a=1&__d=dis) >>>

Username: trymefirst.in, Hashtag: indianskincareroutine, Followers: 8337

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/deeptisehgalsvarasya/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/deeptisehgalsvarasya/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/deeptisehgalsvarasya/?__a=1&__d=dis) >>>

Username: deeptisehgalsvarasya, Hashtag: indianskincareroutine, Followers: 33831

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinskanaturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinskanaturals/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skinskanaturals/?__a=1&__d=dis) >>>

Username: skinskanaturals, Hashtag: indianskincareroutine, Followers: 14055

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautee_n_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautee_n_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/beautee_n_skincare/?__a=1&__d=dis) >>>
Status 404: Endpoint /v1/users/beautee_n_skincare/usernameinfo/ does not exist

❌ Error fetching data for beautee_n_skincare: User not found

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/littlearth_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/littlearth_skincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/littlearth_skincare/?__a=1&__d=dis) >>>

Username: littlearth_skincare, Hashtag: indianskincareroutine, Followers: 1678

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/pbmskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/pbmskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/pbmskincare/?__a=1&__d=dis) >>>

Username: pbmskincare, Hashtag: indianskincareroutine, Followers: 1838

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shine_with_shiny/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shine_with_shiny/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/shine_with_shiny/?__a=1&__d=dis) >>>

Username: shine_with_shiny, Hashtag: indianskincareroutine, Followers: 33

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare.haadiya/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare.haadiya/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincare.haadiya/?__a=1&__d=dis) >>>

Username: skincare.haadiya, Hashtag: indianskincareroutine, Followers: 27998

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/laurarosebeautyblog/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/laurarosebeautyblog/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/laurarosebeautyblog/?__a=1&__d=dis) >>>

Username: laurarosebeautyblog, Hashtag: indianskincareroutine, Followers: 13419

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/arisiaindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/arisiaindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/arisiaindia/?__a=1&__d=dis) >>>

Username: arisiaindia, Hashtag: indianskincareroutine, Followers: 5171

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/demurebeautyin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/demurebeautyin/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/demurebeautyin/?__a=1&__d=dis) >>>

Username: demurebeautyin, Hashtag: indianskincareroutine, Followers: 1159

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowypeachie/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowypeachie/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/glowypeachie/?__a=1&__d=dis) >>>

Username: glowypeachie, Hashtag: indianskincareroutine, Followers: 36626

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/peach.skincare.beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/peach.skincare.beauty/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/peach.skincare.beauty/?__a=1&__d=dis) >>>

Username: peach.skincare.beauty, Hashtag: indianskincareroutine, Followers: 4

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarevilla/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarevilla/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincarevilla/?__a=1&__d=dis) >>>

Username: skincarevilla, Hashtag: indianskincareroutine, Followers: 3012

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tanned_ranjana_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tanned_ranjana_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/tanned_ranjana_/?__a=1&__d=dis) >>>

Username: tanned_ranjana_, Hashtag: indianskincareroutine, Followers: 2931

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chitrasinghofficial/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chitrasinghofficial/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chitrasinghofficial/?__a=1&__d=dis) >>>

Username: chitrasinghofficial, Hashtag: indianskincareroutine, Followers: 20557

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bioretherapy_india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bioretherapy_india/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bioretherapy_india/?__a=1&__d=dis) >>>

Username: bioretherapy_india, Hashtag: indianskincareroutine, Followers: 5167

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_scfanatic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_scfanatic/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_scfanatic/?__a=1&__d=dis) >>>

Username: the_scfanatic, Hashtag: indianskincareroutine, Followers: 1231

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_skincare_world/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_skincare_world/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/the_skincare_world/?__a=1&__d=dis) >>>

Username: the_skincare_world, Hashtag: indianskincareroutine, Followers: 5509

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_myskincarejournal_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_myskincarejournal_/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_myskincarejournal_/?__a=1&__d=dis) >>>

Username: _myskincarejournal_, Hashtag: indianskincareroutine, Followers: 28

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yashhsushi/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yashhsushi/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/yashhsushi/?__a=1&__d=dis) >>>

Username: yashhsushi, Hashtag: indianskincareroutine, Followers: 1240

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cureskinapp/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cureskinapp/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/cureskinapp/?__a=1&__d=dis) >>>

Username: cureskinapp, Hashtag: indianskincareroutine, Followers: 153251

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/strictlyorganicsindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/strictlyorganicsindia/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/strictlyorganicsindia/?__a=1&__d=dis) >>>

Username: strictlyorganicsindia, Hashtag: indianskincareroutine, Followers: 9196

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bellavitapk.official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bellavitapk.official/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/bellavitapk.official/?__a=1&__d=dis) >>>

Username: bellavitapk.official, Hashtag: indianskincareroutine, Followers: 1731

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chocoskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chocoskincare/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/chocoskincare/?__a=1&__d=dis) >>>

Username: chocoskincare, Hashtag: indianskincareroutine, Followers: 1107

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincaresy/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincaresy/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skincaresy/?__a=1&__d=dis) >>>

Username: skincaresy, Hashtag: indianskincareroutine, Followers: 1868

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skindialog/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skindialog/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/skindialog/?__a=1&__d=dis) >>>

Username: skindialog, Hashtag: indianskincareroutine, Followers: 48

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/indianskin.co/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/indianskin.co/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/indianskin.co/?__a=1&__d=dis) >>>

Username: indianskin.co, Hashtag: indianskincareroutine, Followers: 13877

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/menskincareee/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/menskincareee/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/menskincareee/?__a=1&__d=dis) >>>

Username: menskincareee, Hashtag: indianskincareroutine, Followers: 1625

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/infotronicsweb/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/infotronicsweb/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/infotronicsweb/?__a=1&__d=dis) >>>

Username: infotronicsweb, Hashtag: indianskincareroutine, Followers: 3

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_viju_s/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_viju_s/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/_viju_s/?__a=1&__d=dis) >>>

Username: _viju_s, Hashtag: indianskincareroutine, Followers: 2340

Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/dreamyatoms/?__a=1&__d=dis) >>>

KeyboardInterrupt:

In [1]:
import instaloader

L = instaloader.Instaloader()
username = "myplixlife"

# Login with an Instagram account (optional but recommended)
L.login("aakash_sharma_413", "@1234Aakash")

# Get tagged posts
profile = instaloader.Profile.from_username(L.context, username)
for post in profile.get_tagged_posts():
    print(post.url)  # Print the post URL

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=e31a871f7301132ceaab56507a66bbb7&variables=%7B%22id%22%3A8628456936%2C%22first%22%3A12%7D [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=e31a871f7301132ceaab56507a66bbb7&variables=%7B%22id%22%3A8628456936%2C%22first%22%3A12%7D [retrying; skip with ^C]

ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=e31a871f7301132ceaab56507a66bbb7&variables=%7B%22id%22%3A8628456936%2C%22first%22%3A12%7D

In [5]:
import instaloader
import time

# Initialize Instaloader
L = instaloader.Instaloader()

# Instagram Username to Check
username = "myplixlife"

# Load saved session instead of logging in with a password
try:
    L.load_session_from_file("aakash_sharma_413")  # Load existing session
    print("✅ Session loaded successfully!")
except FileNotFoundError:
    print("⚠ Session file not found. Please log in manually first.")
    L.login("aakash_sharma_413", "@1234Aakash")  # One-time manual login
    L.save_session_to_file()  # Save session for future use

# Get tagged posts
try:
    profile = instaloader.Profile.from_username(L.context, username)
    print(f"🔍 Fetching tagged posts for {username}...\n")

    # Loop through tagged posts with rate-limiting
    for post in profile.get_tagged_posts():
        print(post.url)
        time.sleep(10)  # Pause for 10 seconds between requests to avoid blocking

    print("\n✅ Done fetching all tagged posts!")

except instaloader.exceptions.ProfileNotExistsException:
    print("❌ Error: The specified Instagram profile does not exist.")
except instaloader.exceptions.ConnectionException:
    print("❌ Error: Connection issue. Try again later.")
except Exception as e:
    print(f"❌ Unexpected error: {e}")

Loaded session from C:\Users\91954\AppData\Local\Instaloader\session-aakash_sharma_413.
✅ Session loaded successfully!
🔍 Fetching tagged posts for myplixlife...

JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=e31a871f7301132ceaab56507a66bbb7&variables=%7B%22id%22%3A8628456936%2C%22first%22%3A12%7D [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=e31a871f7301132ceaab56507a66bbb7&variables=%7B%22id%22%3A8628456936%2C%22first%22%3A12%7D [retrying; skip with ^C]

❌ Error: Connection issue. Try again later.

In [7]:
import requests
import json
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# Instagram credentials (use your own)
INSTAGRAM_USERNAME = "aakash_sharma_413"
INSTAGRAM_PASSWORD = "@1234Aakash"
USERNAME_TO_FETCH = "myplixlife"  # Target username

# 🔹 Step 1: Log in to Instagram & Get Session ID
def get_instagram_session():
    options = webdriver.ChromeOptions()
    # options.add_argument("--headless")  # Run in headless mode (no UI)
    options.add_argument("--disable-blink-features=AutomationControlled")
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

    driver.get("https://www.instagram.com/accounts/login/")
    time.sleep(5)  # Allow page to load

    # Enter username & password
    driver.find_element(By.NAME, "username").send_keys(INSTAGRAM_USERNAME)
    driver.find_element(By.NAME, "password").send_keys(INSTAGRAM_PASSWORD + Keys.RETURN)
    time.sleep(5)  # Wait for login to complete

    # Get cookies
    cookies = driver.get_cookies()
    driver.quit()

    # Extract sessionid
    sessionid = next((cookie["value"] for cookie in cookies if cookie["name"] == "sessionid"), None)
    if not sessionid:
        raise Exception("❌ Failed to retrieve sessionid!")
    
    print(f"✅ Session ID retrieved: {sessionid}")
    return sessionid

# 🔹 Step 2: Fetch Tagged Posts Using GraphQL
def get_tagged_posts(sessionid):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "Cookie": f"sessionid={sessionid};"
    }

    # Get user ID
    user_info_url = f"https://www.instagram.com/{USERNAME_TO_FETCH}/?__a=1&__d=dis"
    response = requests.get(user_info_url, headers=headers)
    if response.status_code != 200:
        print("❌ Error: Failed to fetch user ID. Check session ID.")
        return

    user_id = response.json()["graphql"]["user"]["id"]

    # Fetch tagged posts
    query_hash = "e31a871f7301132ceaab56507a66bbb7"
    variables = json.dumps({"id": user_id, "first": 10})  # Fetch first 10 posts
    graphql_url = f"https://www.instagram.com/graphql/query?query_hash={query_hash}&variables={variables}"

    response = requests.get(graphql_url, headers=headers)
    if response.status_code != 200:
        print("❌ Error: GraphQL request failed. Instagram might be blocking requests.")
        return

    data = response.json()
    tagged_posts = data["data"]["user"]["edge_user_to_photos_of_you"]["edges"]

    # Print post URLs
    for post in tagged_posts:
        post_node = post["node"]
        print(f"📸 Post: https://www.instagram.com/p/{post_node['shortcode']}/")
        time.sleep(5)  # Delay to avoid rate-limiting

# 🔹 Execute the Functions
session_id = get_instagram_session()
get_tagged_posts(session_id)

✅ Session ID retrieved: 71968213252%3AqBVBnugaavTa3r%3A23%3AAYdaDd1RC2vSfznu-bdTKPWRg13HOPQCsU74NWDsyQ
❌ Error: Failed to fetch user ID. Check session ID.

In [8]:
import requests
import json
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# Instagram credentials (use your own)
INSTAGRAM_USERNAME = "aakash_sharma_413"
INSTAGRAM_PASSWORD = "@1234Aakash"
USERNAME_TO_FETCH = "myplixlife"  # Target username

SESSION_FILE = "sessionid.txt"  # File to store session ID

# 🔹 Step 1: Get Session ID
def get_instagram_session():
    try:
        # Load session ID if it exists
        with open(SESSION_FILE, "r") as f:
            sessionid = f.read().strip()
            if sessionid:
                print(f"✅ Using saved session ID: {sessionid}")
                return sessionid
    except FileNotFoundError:
        pass  # No session file, continue login

    # Start Selenium WebDriver (headless mode)
    options = webdriver.ChromeOptions()
    # options.add_argument("--headless")
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

    driver.get("https://www.instagram.com/accounts/login/")
    time.sleep(5)  # Wait for page to load

    # Enter username & password
    driver.find_element(By.NAME, "username").send_keys(INSTAGRAM_USERNAME)
    driver.find_element(By.NAME, "password").send_keys(INSTAGRAM_PASSWORD + Keys.RETURN)
    time.sleep(5)  # Wait for login to complete

    # Get session ID from cookies
    cookies = driver.get_cookies()
    driver.quit()
    sessionid = next((cookie["value"] for cookie in cookies if cookie["name"] == "sessionid"), None)
    
    if not sessionid:
        raise Exception("❌ Failed to retrieve sessionid!")

    # Save session ID for future use
    with open(SESSION_FILE, "w") as f:
        f.write(sessionid)

    print(f"✅ Session ID retrieved and saved: {sessionid}")
    return sessionid

# 🔹 Step 2: Fetch Tagged Posts Using GraphQL
def get_tagged_posts(sessionid):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "Cookie": f"sessionid={sessionid};"
    }

    # Get user ID
    user_info_url = f"https://www.instagram.com/{USERNAME_TO_FETCH}/?__a=1&__d=dis"
    response = requests.get(user_info_url, headers=headers)

    if response.status_code != 200:
        print(f"❌ Error: Failed to fetch user ID. Status Code: {response.status_code}")
        print("🔍 Response:", response.text)
        return

    user_data = response.json()
    user_id = user_data.get("graphql", {}).get("user", {}).get("id")

    if not user_id:
        print("❌ Error: Unable to extract user ID. Instagram may have changed the API.")
        return

    # Fetch tagged posts
    query_hash = "e31a871f7301132ceaab56507a66bbb7"
    variables = json.dumps({"id": user_id, "first": 10})  # Fetch first 10 posts
    graphql_url = f"https://www.instagram.com/graphql/query?query_hash={query_hash}&variables={variables}"

    response = requests.get(graphql_url, headers=headers)
    if response.status_code != 200:
        print(f"❌ Error: GraphQL request failed. Status Code: {response.status_code}")
        print("🔍 Response:", response.text)
        return

    data = response.json()
    tagged_posts = data.get("data", {}).get("user", {}).get("edge_user_to_photos_of_you", {}).get("edges", [])

    # Print post URLs
    for post in tagged_posts:
        post_node = post["node"]
        print(f"📸 Post: https://www.instagram.com/p/{post_node['shortcode']}/")
        time.sleep(5)  # Delay to avoid rate-limiting

# 🔹 Execute the Functions
session_id = get_instagram_session()
get_tagged_posts(session_id)

✅ Session ID retrieved and saved: 71968213252%3Aq5p8iJEHj5yTWP%3A17%3AAYeNpoq_tu4Jf3YR8WrHOKiSOzr4Y2zvXlTFk5sq5w
❌ Error: Failed to fetch user ID. Status Code: 201
🔍 Response:

In [2]:
import instaloader

L = instaloader.Instaloader()
L.load_session_from_file("aakash_sharma_413")  # Load saved session

username = "myplixlife"
profile = instaloader.Profile.from_username(L.context, username)

for post in profile.get_tagged_posts():
    print(post.url)

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\91954\\appdata\\local\\temp/.instaloader-91954/session-aakash_sharma_413'